version:  '2'
services:

  mysqldb:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      default:
        ipv4_address: 172.16.0.115
    extra_hosts:
      - "hive-master:172.16.0.110"
      - "hive-slave1:172.16.0.111"
      - "hive-slave2:172.16.0.112"
      - "hive-slave3:172.16.0.113"
      - "hive-slave4:172.16.0.114"
    hostname: mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: whg19961119
      # MYSQL_USER: hive
      # MYSQL_PASSWORD: hive

  master:
    image: solomonfield/hive:2.3.3-centos
    container_name: hive-master
    networks:
      default:
        ipv4_address: 172.16.0.110
    extra_hosts:
      - "hive-slave1:172.16.0.111"
      - "hive-slave2:172.16.0.112"
      - "hive-slave3:172.16.0.113"
      - "hive-slave4:172.16.0.114"
      - "mysql:172.16.0.115"
    hostname: hive-master
    ports: 
      - "19010:22"
      - "50070:50070"
      - "8088:8088"
      - "16010:16010"
    environment:
      ZK_ID: 1
      ROLE: master
    volumes:
      - ~/Public/repo/BasicTask/section_three/dockerfiles/share/:/root/experiment/
    tty: true
    stdin_open: true

  slave1:
    image: solomonfield/hive:2.3.3-centos
    container_name: hive-slave1
    networks:
      default:
        ipv4_address: 172.16.0.111
    extra_hosts:
      - "hive-master:172.16.0.110"
      - "hive-slave2:172.16.0.112"
      - "hive-slave3:172.16.0.113"
      - "hive-slave4:172.16.0.114"
      - "mysql:172.16.0.115"
    hostname: hive-slave1
    ports: 
      - "19011:22"
    environment:
      ZK_ID: 2
      ROLE: slave
    tty: true
    stdin_open: true

  slave2:
    image: solomonfield/hive:2.3.3-centos
    container_name: hive-slave2
    networks:
      default:
        ipv4_address: 172.16.0.112
    extra_hosts:
      - "hive-master:172.16.0.110"
      - "hive-slave1:172.16.0.111"
      - "hive-slave3:172.16.0.113"
      - "hive-slave4:172.16.0.114"
      - "mysql:172.16.0.115"
    hostname: hive-slave2
    ports: 
      - "19012:22"
    environment:
      ZK_ID: 3
      ROLE: slave
    tty: true
    stdin_open: true

  slave3:
    image: solomonfield/hive:2.3.3-centos
    container_name: hive-slave3
    networks:
      default:
        ipv4_address: 172.16.0.113
    extra_hosts:
      - "hive-master:172.16.0.110"
      - "hive-slave1:172.16.0.111"
      - "hive-slave2:172.16.0.112"
      - "hive-slave4:172.16.0.114"
      - "mysql:172.16.0.115"
    hostname: hive-slave3
    ports: 
      - "19013:22"
    environment:
      ZK_ID: 4
      ROLE: slave
    tty: true
    stdin_open: true

  slave4:
    image: solomonfield/hive:2.3.3-centos
    container_name: hive-slave4  
    networks:
      default:
        ipv4_address: 172.16.0.114
    extra_hosts:
      - "hive-master:172.16.0.110"
      - "hive-slave1:172.16.0.111"
      - "hive-slave2:172.16.0.112"
      - "hive-slave3:172.16.0.113"
      - "mysql:172.16.0.115"
    hostname: hive-slave4
    ports: 
      - "19014:22"
    environment:
      ZK_ID: 5
      ROLE: slave
    tty: true
    stdin_open: true


networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/16
        gateway: 172.16.0.249

