version:  '2'
services:

  master:
    image: solomonfield/hbase:2.1.0
    container_name: hbase-master
    networks:
      default:
        ipv4_address: 172.18.0.110
    extra_hosts:
      - "hbase-slave1:172.18.0.111"
      - "hbase-slave2:172.18.0.112"
      - "hbase-slave3:172.18.0.113"
      - "hbase-slave4:172.18.0.114"
    hostname: hbase-master
    ports: 
      - "19010:22"
      - "50070:50070"
      - "8088:8088"
      - "16010:16010"
    volumes:
      - ~/Public/repo/BasicTask/PASA_CLASS/dockerfiles/share/:/root/experiment/
    environment:
      ZK_ID: 1
      ROLE: master
    tty: true
    stdin_open: true

  slave1:
    image: solomonfield/hbase:2.1.0
    container_name: hbase-slave1
    networks:
      default:
        ipv4_address: 172.18.0.111
    extra_hosts:
      - "hbase-master:172.18.0.110"
      - "hbase-slave2:172.18.0.112"
      - "hbase-slave3:172.18.0.113"
      - "hbase-slave4:172.18.0.114"
    hostname: hbase-slave1
    ports: 
      - "19011:22"
    environment:
      ZK_ID: 2
      ROLE: slave
    tty: true
    stdin_open: true

  slave2:
    image: solomonfield/hbase:2.1.0
    container_name: hbase-slave2
    networks:
      default:
        ipv4_address: 172.18.0.112
    extra_hosts:
      - "hbase-master:172.18.0.110"
      - "hbase-slave1:172.18.0.111"
      - "hbase-slave3:172.18.0.113"
      - "hbase-slave4:172.18.0.114"
    hostname: hbase-slave2
    ports: 
      - "19012:22"
    environment:
      ZK_ID: 3
      ROLE: slave
    tty: true
    stdin_open: true

  slave3:
    image: solomonfield/hbase:2.1.0
    container_name: hbase-slave3
    networks:
      default:
        ipv4_address: 172.18.0.113
    extra_hosts:
      - "hbase-master:172.18.0.110"
      - "hbase-slave1:172.18.0.111"
      - "hbase-slave2:172.18.0.112"
      - "hbase-slave4:172.18.0.114"
    hostname: hbase-slave3
    ports: 
      - "19013:22"
    environment:
      ZK_ID: 4
      ROLE: slave
    tty: true
    stdin_open: true

  slave4:
    image: solomonfield/hbase:2.1.0
    container_name: hbase-slave4  
    networks:
      default:
        ipv4_address: 172.18.0.114
    extra_hosts:
      - "hbase-master:172.18.0.110"
      - "hbase-slave1:172.18.0.111"
      - "hbase-slave2:172.18.0.112"
      - "hbase-slave3:172.18.0.113"
    hostname: hbase-slave4
    ports: 
      - "19014:22"
    environment:
      ZK_ID: 5
      ROLE: slave
    tty: true
    stdin_open: true

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
        gateway: 172.18.0.249

